language: python3
branches:
    only:
        master
install:
    - git clone --recurse-submodules https://github.com/illinois-cs241/illinois-cs241.github.io.git site
    - git config credential.helper "store --file=.git/credentials"; echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials 2>/dev/null
    - git config --global user.email "bhuvan.venkatesh21@gmail.com"
    - git config --global user.name "Bhuvan Venkatesh"
    - git remote add token-origin https://${GH_TOKEN}@github.com/illinois-cs241/illinois-cs241.github.io.git > /dev/null 2>&1
    - cd site/; git checkout develop; cd _docs/; git pull origin; cd ..; git add _docs; git commit -m "Updating docs to $(git ls-tree master _docs/)"; git push --quiet --set-upstream token-origin develop
