language: python3
branches:
    only:
        master
install:
    - git clone --recurse-submodules https://github.com/illinois-cs241/illinois-cs241.github.io.git site
    - cd site/
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials 2>/dev/null
    - git config --global user.email "bhuvan.venkatesh21@gmail.com"
    - git config --global user.name "Bhuvan Venkatesh"
    - git remote add token-origin "https://${GITHUB_TOKEN}@github.com/illinois-cs241/illinois-cs241.github.io.git" > /dev/null 2>&1
    - git checkout develop
    - cd _docs/
    - git pull origin master
    - cd ..
    - git add _docs
    - git commit -m "Updating docs to $(git ls-tree master _docs/)"
    - git push --quiet token-origin develop

