language: python3
branches:
    only:
        master
install:
    - git clone https://github.com/illinois-cs241/illinois-cs241.github.io.git site
    - git config credential.helper "store --file=.git/credentials"; echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials 2>/dev/null
    - git config --global user.email "bhuvan.venkatesh21@gmail.com"
    - git config --global user.name "Bhuvan Venkatesh"
    - cd site/; git checkout develop; cd docs/; git pull origin master; git commit -m "Updating docs to $(git rev-parse master)"
